import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import { TRPCReactProvider } from "~/trpc/react";
import ResponsiveAppBar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Fitness Analytics",
  description: "Generated by Moritz Foglia",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
            <ResponsiveAppBar />
            {children}
            <Analytics />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
